### PR TITLE
Fix InterApplicationBus hooks 

### LINKED ISSUE #43: InterApplicationBus hooks not working
**Affected hooks:**
useInterApplicationBusSend
useInterApplicationPublish
useInterApplicationSubscribe

**Broken in this commit:**
0427cb8accf79f6c41958d75dbfe6c9e35ea20ee

**Leads to the following error when using the useInterApplicationPublish hook in a local demo app (not the one in the README):**
TypeError: Cannot read property 'publish' of undefined

image

### PR DESCRIPTION
**Pull request by ms14981**
These were using an undefined openfin object.

Fixes #43

### CODE REVIEW

File: src/useInterApplicationBusPublish.ts [hunk 1]
```diff
@@ -11,7 +11,7 @@ export default <T>(topic: string, message: T) => {
     };
 
     useEffect(() => {
-        const fin: any = window;
+        const fin: any = (window as any).fin;
```
Comment (oriondean) [inline src/useInterApplicationBusPublish.ts]: Rather than casting to `any`, could we add `fin` to the Window interface?

e.g. create a` globals.d.ts` file in `src` with:
```
import {Fin} from "openfin/_v2/main";

declare global {
    // tslint:disable-next-line:interface-name
    interface Window {
        fin: Fin;
    }
}
```
